(in-package segway_rmp200-msg)
(export '(HEADER-VAL
          PITCH_ANGLE-VAL
          PITCH_RATE-VAL
          ROLL_ANGLE-VAL
          ROLL_RATE-VAL
          LEFT_WHEEL_VELOCITY-VAL
          RIGHT_WHEEL_VELOCITY-VAL
          YAW_RATE-VAL
          SERVO_FRAMES-VAL
          LEFT_WHEEL_DISPLACEMENT-VAL
          RIGHT_WHEEL_DISPLACEMENT-VAL
          FORWARD_DISPLACEMENT-VAL
          YAW_DISPLACEMENT-VAL
          LEFT_MOTOR_TORQUE-VAL
          RIGHT_MOTOR_TORQUE-VAL
          OPERATION_MODE-VAL
          GAIN_SCHEDULE-VAL
          UI_BATTERY-VAL
          POWERBASE_BATTERY-VAL
))
